"""initial schema with users, alerts, brands, categories, and item_history

Revision ID: dd9da07806bc
Revises: 
Create Date: 2025-12-02 21:10:36.769566+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9da07806bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vinted_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_country_name', 'brands', ['country_code', 'name'], unique=False)
    op.create_index('idx_brand_country_vinted_id', 'brands', ['country_code', 'vinted_id'], unique=False)
    op.create_index(op.f('ix_brands_country_code'), 'brands', ['country_code'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vinted_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_country_name', 'categories', ['country_code', 'name'], unique=False)
    op.create_index('idx_category_country_parent', 'categories', ['country_code', 'parent_id'], unique=False)
    op.create_index('idx_category_country_vinted_id', 'categories', ['country_code', 'vinted_id'], unique=False)
    op.create_index(op.f('ix_categories_country_code'), 'categories', ['country_code'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('search_text', sa.String(length=500), nullable=True),
    sa.Column('brand_ids', sa.Text(), nullable=True),
    sa.Column('brand_names', sa.Text(), nullable=True),
    sa.Column('catalog_ids', sa.Text(), nullable=True),
    sa.Column('catalog_names', sa.Text(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sizes', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('notification_config', sa.JSON(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_found_count', sa.Integer(), nullable=False),
    sa.Column('total_found_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_country_code'), 'alerts', ['country_code'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('item_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_item', 'item_history', ['alert_id', 'item_id'], unique=True)
    op.create_index('idx_found_at', 'item_history', ['found_at'], unique=False)
    op.create_index(op.f('ix_item_history_alert_id'), 'item_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_item_history_item_id'), 'item_history', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_history_item_id'), table_name='item_history')
    op.drop_index(op.f('ix_item_history_alert_id'), table_name='item_history')
    op.drop_index('idx_found_at', table_name='item_history')
    op.drop_index('idx_alert_item', table_name='item_history')
    op.drop_table('item_history')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_country_code'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_country_code'), table_name='categories')
    op.drop_index('idx_category_country_vinted_id', table_name='categories')
    op.drop_index('idx_category_country_parent', table_name='categories')
    op.drop_index('idx_category_country_name', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_country_code'), table_name='brands')
    op.drop_index('idx_brand_country_vinted_id', table_name='brands')
    op.drop_index('idx_brand_country_name', table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
